[project]
name = "llm-svg-generator-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.122.0",
    "httpx>=0.28.1",
    "ruff>=0.14.6",
    "uvicorn>=0.38.0",
]
